spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloggydb
    username: bloggy
    password: bloggy
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  properties:
    hibernate:
      format_sql: true

app:
  hostname: e
  token:
    header: X-BLOGGY-TOKEN
    prefix: bltoken=
    secret: abcdefg
    expiration: 1800000
  login:
    tries: 3
    breaktime:

email:
  smtp:
    host: a
    port: 993
  username: a
  password: b
  template:
    auth:
      activation:
        subject:
        body:
      confirmation:
        subject:
        body:
      reset:
        subject:
        body:



