spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloggydb
    username: bloggy
    password: bloggy
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  properties:
    hibernate:
      format_sql: true

server:
  port: 8090
  servlet:
    session:
      cookie:
        name: bloggytoken
        secure: false
        http-only: false
        max-age: 9999999

app:
  hostname: e
  auth:
    signin:
      tries: 3
      breaktime: 1
    signup:
      lifetime: 3

email:
  smtp:
    host: a
    port: 993
  username: a
  password: b
  template:
    auth:
      activation:
        subject:
        body:
      confirmation:
        subject:
        body:
      reset:
        subject:
        body:
      success:
        subject:
        body:



